CREATE DATABASE ENERGYDB_correct;
USE ENERGYDB_correct;
-- COUNTRY TABLE
CREATE TABLE COUNTRY(
     CID VARCHAR(10) PRIMARY KEY,
    Country VARCHAR(100) UNIQUE
);

SELECT * FROM COUNTRY;

-- 2. emission_3 table

CREATE TABLE emission_3 (
    country VARCHAR(100),
    energy_type VARCHAR(50),
    year INT,
    emission DOUBLE,
    per_capita_emission DOUBLE,
    FOREIGN KEY (country) REFERENCES country(Country)
);
DROP TABLE EMISSION_3;
CREATE TABLE EMISSION_TEMP(
country VARCHAR(100),
energy_type VARCHAR(50),
year varchar(10),
emission varchar(50),
per_capita_emission varchar(50)
);


INSERT INTO emission_3 (country, energy_type, year, emission, per_capita_emission)
SELECT
    country,
    energy_type,
    CAST(year AS UNSIGNED),
    CASE WHEN emission = '' THEN NULL ELSE CAST(emission AS DOUBLE) END,
    CASE WHEN per_capita_emission = '' THEN NULL ELSE CAST(per_capita_emission AS DOUBLE) END
FROM EMISSION_TEMP;


select count(*) from gdp_3;
-- 3. population table
CREATE TABLE population (
    countries VARCHAR(100),
    year INT,
    Value DOUBLE,
    FOREIGN KEY (countries) REFERENCES country(Country)
);
DROP TABLE POPULATION;

CREATE TABLE POPULATION_TEMP(
country VARCHAR(100),
year varchar(10),
Value varchar(50)
);

INSERT INTO population (countries, year, Value)
SELECT
    country,
    CAST(year AS UNSIGNED),
    CASE WHEN Value = '' THEN NULL
         ELSE CAST(Value AS DOUBLE)
    END
FROM POPULATION_TEMP;

SELECT COUNT(*) FROM POPULATION;
-- 4. production table
CREATE TABLE production (
    country VARCHAR(100),
    energy VARCHAR(50),
    year INT,
    production DECIMAL(20,10) NULL,
    FOREIGN KEY (country) REFERENCES country(Country)
);
DROP TABLE EMISSION_3;
-- 5. gdp_3 table
CREATE TABLE gdp_3 (
    Country VARCHAR(100),
    year INT,
    Value DOUBLE,
    FOREIGN KEY (Country) REFERENCES country(Country)
);

-- 6. consumption table
CREATE TABLE consumption (
    country VARCHAR(100),
    energy VARCHAR(50),
    year INT,
    consumption DECIMAL(20,10) NULL,  -- very high precision
    FOREIGN KEY (country) REFERENCES country(Country)
);
SELECT COUNT(*) FROM consumption;        -- should be 5281
SELECT COUNT(*) FROM consumption WHERE consumption IS NULL;  -- should be 4
DROP TABLE CONSUMPTION;
CREATE TABLE CONSUMPTION_TEMP(
country VARCHAR(100),
energy varchar(50),
year varchar(10),
consumption varchar(50)
);

CREATE TABLE PRODUCTION_TEMP(
country varchar(100),
energy varchar(50),
year varchar(10),
production varchar(50)
);

INSERT INTO PRODUCTION(country,energy,year,production)
SELECT country, energy,CAST(year as UNSIGNED), 
CASE 
WHEN production = '' THEN NULL 
ELSE CAST(production AS DECIMAL(20,10))
END
FROM PRODUCTION_TEMP;

SELECT * FROM CONSUMPTION WHERE CONSUMPTION IS NULL;


DROP TABLE CONSUMPTION;
DROP TABLE CONSUMPTION_TEMP;
SELECT * FROM PRODUCTION;
select count(*) from production;

INSERT INTO consumption (country, energy, year, consumption)
SELECT
    country,
    energy,
    CAST(year AS UNSIGNED),
    CASE 
        WHEN consumption = '' THEN NULL   -- empty string → NULL
        ELSE CAST(consumption AS DECIMAL(20,10))
    END
FROM CONSUMPTION_TEMP;


SELECT * FROM CONSUMPTION;


SELECT * FROM emission_3;

SELECT COUNT(*) AS row_count
FROM consumption;
select * from emission_3;

SELECT *, MAX(YEAR) OVER (PARTITION BY COUNTRY) AS max_year
FROM GDP_3;


-- so lets rename emission_3 to something else so that we can use emission_3 as view name,
-- no need to change all queries
RENAME TABLE EMISSION_3 TO EMISSION;
-- 1) What is the total emission per country for the most recent year available? (country wise recent year)
-- Identify most recent year for all coutries,,
-- Then sum of emissions of that particular year  

-- SUB QUERY 

CREATE VIEW EMISSION_3 AS
SELECT * FROM EMISSION WHERE ENERGY_TYPE <> "CO2 emissions (MMtonnes CO2)";

SELECT COUNTRY, YEAR, ROUND(EMISSION,2) AS TOTAL_EMISSION 
FROM EMISSION_TOTAL
WHERE (COUNTRY, YEAR) IN (
	SELECT COUNTRY, MAX(YEAR) 
	FROM EMISSION_3 
    GROUP BY COUNTRY
)
ORDER BY TOTAL_EMISSION DESC 
LIMIT 5;



USE ENERGYDB_CORRECT;

SELECT * FROM GDP_3;

-- 2) What are the top 5 countries by GDP in the most recent year?
-- With this check I gotta know every gdp has only one row per country per year
SELECT
  COUNTRY,
  YEAR,
  COUNT(*) AS row_count
FROM GDP_3
GROUP BY COUNTRY, YEAR
HAVING COUNT(*) > 1; 

-- this is for country wise year 
select * from gdp_3;
SELECT G1.COUNTRY, G1.VALUE AS GDP FROM GDP_3 G1
JOIN (SELECT COUNTRY, MAX(YEAR) AS RECENT_YEAR FROM GDP_3 GROUP BY COUNTRY) G2
ON G1.COUNTRY = G2.COUNTRY AND G1.YEAR = G2.RECENT_YEAR
ORDER BY GDP DESC
LIMIT 5;

-- Global year

-- using window functions

SELECT COUNTRY, YEAR, VALUE AS GDP 
FROM (
SELECT COUNTRY, YEAR, VALUE, ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY YEAR DESC) AS R
FROM GDP_3) T
WHERE R = 1
ORDER BY GDP DESC
LIMIT 5;
select * from gdp_3;

-- In the most recent year so global



SELECT COUNTRY, YEAR , VALUE AS GDP 
FROM GDP_3
WHERE YEAR = (SELECT MAX(YEAR) FROM GDP_3)
ORDER BY VALUE DESC
LIMIT 5;
SELECT * FROM GDP_3;

SELECT DISTINCT ENERGY FROM CONSUMPTION_V;
-- 3) Compare energy production and consumption by country and year. 
-- so for production and consumption also we will create views
RENAME TABLE PRODUCTION TO PRODUCTION_V;
RENAME TABLE CONSUMPTION TO CONSUMPTION_V;

CREATE VIEW PRODUCTION AS
SELECT * FROM PRODUCTION_V WHERE ENERGY <>  'Nuclear, renewables, and other (quad Btu)';

CREATE VIEW CONSUMPTION AS 
SELECT * FROM CONSUMPTION_V WHERE ENERGY <> 'Nuclear, renewables, and other (quad Btu)';

SELECT * FROM CONSUMPTION;
SELECT ENERGY_STATUS, COUNT(*) AS COUNT
FROM (
SELECT P.COUNTRY,
	   P.YEAR, 
       SUM(P.PRODUCTION) AS TOTAL_PRODUCTION,
	   SUM(C.CONSUMPTION) AS TOTAL_CONSUMPTION,
       SUM(P.PRODUCTION) - SUM(C.CONSUMPTION) AS NET_COMPARISON, 
	   CASE
			WHEN SUM(P.PRODUCTION) > SUM(C.CONSUMPTION) THEN "SURPLUS"
            WHEN SUM(P.PRODUCTION) < SUM(C.CONSUMPTION) THEN "DEFICIT"
		    ELSE "BALANCED"
	   END AS ENERGY_STATUS
FROM PRODUCTION P
JOIN CONSUMPTION C 
ON P.COUNTRY = C.COUNTRY
AND P.YEAR = C.YEAR 
AND P.ENERGY = C.ENERGY 
GROUP BY P.COUNTRY, P.YEAR
ORDER BY P.COUNTRY, P.YEAR
) AS sub
GROUP BY ENERGY_STATUS;

-- jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj 

SELECT ENERGY_STATUS, COUNT(*) AS TOTAL_COUNT, ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(),2) AS PERCENTAGE
FROM(
SELECT P.COUNTRY,
	   P.YEAR, 
       SUM(P.PRODUCTION) AS TOTAL_PRODUCTION,
	   SUM(C.CONSUMPTION) AS TOTAL_CONSUMPTION,
       SUM(P.PRODUCTION) - SUM(C.CONSUMPTION) AS NET_COMPARISON, 
	   CASE
			WHEN SUM(P.PRODUCTION) > SUM(C.CONSUMPTION) THEN "SURPLUS"
            WHEN SUM(P.PRODUCTION) < SUM(C.CONSUMPTION) THEN "DEFICIT"
		    ELSE "BALANCED"
	   END AS ENERGY_STATUS
FROM PRODUCTION P
JOIN CONSUMPTION C 
ON P.COUNTRY = C.COUNTRY
AND P.YEAR = C.YEAR 
AND P.ENERGY = C.ENERGY 
GROUP BY P.COUNTRY, P.YEAR
ORDER BY P.COUNTRY, P.YEAR
) AS T
GROUP BY ENERGY_STATUS;

-- 4) Which energy types contribute most to emissions across all countries?
SELECT ENERGY_TYPE, ROUND(SUM(EMISSION), 2) AS TOTAL_EMISSION 
FROM EMISSION_3
GROUP BY ENERGY_TYPE 
ORDER BY TOTAL_EMISSION DESC;
SELECT distinct energy FROM CONSUMPTION ;

-- 5) How have global emissions changed year over year?
-- creating a view for total_emission of all energy_types which is in CO2,
-- so only considering CO2 rows  

CREATE VIEW EMISSION_TOTAL AS
SELECT * FROM EMISSION WHERE ENERGY_TYPE = 'CO2 emissions (MMtonnes CO2)';


SELECT * FROM EMISSION_TOTAL;
SELECT YEAR, SUM(EMISSION) AS TOTAL_EMISSION FROM EMISSION_3
GROUP BY YEAR
ORDER BY YEAR;
SELECT YEAR, SUM(EMISSION) FROM EMISSION_TOTAL GROUP BY YEAR;
SELECT YEAR, SUM(EMISSION) FROM EMISSION GROUP BY YEAR;
SELECT YEAR, SUM(EMISSION) FROM EMISSION_C GROUP BY YEAR;

WITH YEAR_DATA AS(
SELECT YEAR, SUM(EMISSION) AS TOTAL_EMISSION,
SUM(EMISSION) - LAG(SUM(EMISSION)) OVER (ORDER BY YEAR) AS Y_T_Y_CHANGE
FROM EMISSION_TOTAL
GROUP BY YEAR
)
SELECT YEAR, TOTAL_EMISSION, Y_T_Y_CHANGE,
CASE 
WHEN Y_T_Y_CHANGE IS NULL THEN "Starting year"
WHEN Y_T_Y_CHANGE > 0 THEN "INCREASED"
WHEN Y_T_Y_CHANGE < 0 THEN "DECREASED"
ELSE "NO CHANGE"
END AS GLOBAL_CHANGE
FROM YEAR_DATA
ORDER BY YEAR;








SELECT YEAR, SUM(EMISSION) AS TOTAL_EMISSION, SUM(EMISSION) - LAG(SUM(EMISSION)) OVER (ORDER BY YEAR) AS 
Y_T_Y_CHANGE FROM EMISSION_3 GROUP BY YEAR; 


-- 6) What is the trend in GDP for each country over the given years?

WITH GDP_DATA AS(
SELECT COUNTRY, YEAR, VALUE, 
LAG(VALUE) OVER (PARTITION BY COUNTRY ORDER BY YEAR) AS PREV_GDP
FROM GDP_3)

SELECT COUNTRY, YEAR, VALUE AS GDP,
ROUND(VALUE - PREV_GDP,4) AS DIFFERENCE,
CASE
WHEN VALUE > PREV_GDP
THEN "Increased"
WHEN VALUE < PREV_GDP
THEN "Decreased"
ELSE "No change"
END AS DIRECTION
FROM GDP_DATA
ORDER BY COUNTRY, YEAR;

-- 7) How has population growth affected total emissions in each country?

WITH EMISSION_POP_TREND AS(
SELECT E.COUNTRY, E.YEAR, E.EMISSION, P.VALUE AS POPULATION, 
(E.EMISSION - LAG(E.EMISSION) OVER (PARTITION BY E.COUNTRY ORDER BY E.YEAR)) AS EMI_CHANGE,
(P.VALUE - LAG(P.VALUE) OVER (PARTITION BY P.COUNTRIES ORDER BY P.YEAR)) AS POP_CHANGE
FROM EMISSION_TOTAL E
JOIN POPULATION P 
ON E.COUNTRY = P.COUNTRIES AND
E.YEAR = P.YEAR)
SELECT COUNTRY, YEAR, EMISSION, POPULATION, EMI_CHANGE,POP_CHANGE,
CASE 
WHEN EMI_CHANGE IS NULL THEN "START_YEAR"
WHEN EMI_CHANGE > 0 THEN "Emission increased"
WHEN EMI_CHANGE < 0 THEN "Emission decreased"
ELSE "NO CHANGE"
END AS EMISSION_TREND,
CASE 
WHEN POP_CHANGE IS NULL THEN "START_YEAR"
WHEN POP_CHANGE > 0 THEN "Population increased"
WHEN POP_CHANGE < 0 THEN "Population decreased"
ELSE "NO CHANGE"
END AS POPULATION_TREND
FROM EMISSION_POP_TREND
ORDER BY COUNTRY, YEAR;




select * from consumption;

-- 8) Has energy consumption increased or decreased over the years for major economies? 

WITH MAJ_ECO AS(
SELECT COUNTRY, SUM(VALUE) AS TOTAL_GDP FROM GDP_3 GROUP BY COUNTRY ORDER BY TOTAL_GDP DESC LIMIT 2
),
TOT_CON AS(
SELECT COUNTRY, YEAR, SUM(CONSUMPTION) AS TOTAL_CONSUMPTION
FROM CONSUMPTION group by COUNTRY, YEAR),
CT AS(
SELECT COUNTRY, YEAR, TOTAL_CONSUMPTION,
LAG(TOTAL_CONSUMPTION) OVER (PARTITION BY COUNTRY ORDER BY YEAR) AS PREV_CONS
FROM TOT_CON
)
SELECT CT.COUNTRY, CT.YEAR, CT.TOTAL_CONSUMPTION,
CT.TOTAL_CONSUMPTION - CT.PREV_CONS AS CONSUMPTION_CHANGE ,
CASE 
WHEN PREV_CONS IS NULL THEN "First Year"
WHEN TOTAL_CONSUMPTION > PREV_CONS THEN "Increased"
WHEN TOTAL_CONSUMPTION < PREV_CONS THEN "Decreased"
ELSE "No change"
END AS CON_TREND
FROM CT WHERE CT.COUNTRY IN (SELECT COUNTRY FROM MAJ_ECO)
ORDER BY COUNTRY, YEAR;

-- 9) What is the average yearly change in emissions per capita for each country?
WITH A AS(
SELECT E.COUNTRY, E.YEAR, 
(E.EMISSION/P.VALUE) - LAG(E.EMISSION/P.VALUE) OVER (PARTITION BY E.COUNTRY ORDER BY E.YEAR)
AS YOY_CHANGE_PCE FROM EMISSION_TOTAL E
JOIN POPULATION P
ON E.COUNTRY = P.COUNTRIES AND 
E.YEAR = P.YEAR
)
SELECT COUNTRY, AVG(YOY_CHANGE_PCE) AS AVG_YOY_PCE
FROM A 
GROUP BY COUNTRY
ORDER BY AVG_YOY_PCE DESC;




-- 10) What is the emission-to-GDP ratio for each country by year?

SELECT 
	E.COUNTRY, 
	E.YEAR, 
	ROUND(E.EMISSION/G.VALUE, 4) AS EMISSION_GDP_RATIO
FROM EMISSION_TOTAL E 
JOIN GDP_3 G
	ON E.COUNTRY = G.COUNTRY 
	AND E.YEAR = G.YEAR
ORDER BY E.COUNTRY, E.YEAR;


-- 11) What is the energy consumption per capita for each country over the last decade?
SELECT 
	C.COUNTRY,
    C.YEAR,
    ROUND(C.TOTAL_CONSUMPTION/P.VALUE, 8) AS PER_CAPITA_CONS
FROM (
	SELECT 
		COUNTRY, 
        YEAR, 
        SUM(CONSUMPTION) AS TOTAL_CONSUMPTION 
	FROM CONSUMPTION
	GROUP BY COUNTRY, YEAR
) C
JOIN POPULATION P
	ON C.COUNTRY = P.COUNTRIES 
    AND	C.YEAR = P.YEAR
ORDER BY C.COUNTRY, C.YEAR;




-- What are the top 10 countries by population and how do their emissions compare?
WITH LATEST_YEAR AS(
SELECT LEAST(
(SELECT MAX(YEAR)  FROM POPULATION),
(SELECT MAX(YEAR)  FROM EMISSION_TOTAL))
 AS YEAR_TO_USE
),
TOP_COUN AS(
SELECT COUNTRIES, VALUE AS POPULATION FROM POPULATION 
WHERE YEAR = (SELECT YEAR_TO_USE FROM LATEST_YEAR)
ORDER BY VALUE DESC LIMIT 10)
SELECT T.COUNTRIES,T.POPULATION, E.EMISSION  FROM TOP_COUN T 
JOIN EMISSION_TOTAL E
ON T.COUNTRIES = E.COUNTRY
AND E.YEAR = (SELECT YEAR_TO_USE FROM LATEST_YEAR)
ORDER BY E.EMISSION DESC;


-- WITH TOP_COUN AS(
-- SELECT COUNTRIES, VALUE AS POPULATION FROM POPULATION
-- WHERE YEAR = (SELECT MAX(YEAR) FROM POPULATION) ORDER BY VALUE DESC LIMIT 10
-- )
-- What is the correlation between GDP growth and energy production growth?

WITH TOT_PRO AS(
SELECT COUNTRY, YEAR, SUM(PRODUCTION) AS TOTAL_PRODUCTION FROM PRODUCTION GROUP BY COUNTRY, YEAR
),
TREND AS(
SELECT P.COUNTRY, P.YEAR, G.VALUE AS GDP, P.TOTAL_PRODUCTION AS PRODUCTION ,
G.VALUE - LAG(G.VALUE) OVER (PARTITION BY COUNTRY ORDER BY YEAR) AS GDP_CHANGE,
P.TOTAL_PRODUCTION - LAG(P.TOTAL_PRODUCTION) OVER (PARTITION BY COUNTRY ORDER BY YEAR) AS PROD_CHANGE
FROM TOT_PRO P 
JOIN GDP_3 G ON
P.COUNTRY = G.COUNTRY AND
P.YEAR = G.YEAR
ORDER BY COUNTRY, YEAR
)
SELECT *,
CASE 
WHEN GDP_CHANGE IS NULL THEN "STARTING YEAR"
WHEN GDP_CHANGE < 0 THEN "GDP Decreased"
WHEN GDP_CHANGE > 0 THEN "GDP Increased"
ELSE "NO CHANGE"
END AS GDP_TREND,
CASE
WHEN PROD_CHANGE IS NULL THEN "STARTING YEAR"
WHEN PROD_CHANGE < 0 THEN "PROD Decreased"
WHEN PROD_CHANGE > 0 THEN "PROD Increased"
ELSE "NO CHANGE"
END AS PROD_TREND
FROM TREND;


-- 13) Which countries have the highest energy consumption relative to GDP?
WITH CON AS(
SELECT COUNTRY, YEAR, SUM(CONSUMPTION) AS TOTAL_CONS FROM CONSUMPTION GROUP BY COUNTRY , YEAR
),

RATIO AS(
SELECT C.COUNTRY, C.YEAR, (C.TOTAL_CONS/G.VALUE) AS RATIO FROM CON C
JOIN GDP_3 G ON
C.COUNTRY = G.COUNTRY AND
C.YEAR = G.YEAR
)

SELECT COUNTRY, AVG(RATIO) AS AVG_ENERGY_RATIO FROM RATIO
GROUP BY COUNTRY 
ORDER BY AVG_ENERGY_RATIO DESC LIMIT 10;


-- How does energy production per capita vary across countries?
-- Production per capita = Total Production / Population

WITH PRO AS(
SELECT COUNTRY, YEAR, SUM(PRODUCTION) AS TOTAL_PRODUCTION FROM PRODUCTION GROUP BY COUNTRY,year
),
PER_CAPITA AS(
SELECT P.COUNTRY, P.YEAR, (P.TOTAL_PRODUCTION/PO.VALUE) AS PER_CAPITA_PROD FROM PRO P
JOIN POPULATION PO ON 
P.COUNTRY = PO.COUNTRIES AND
P.YEAR = PO.YEAR
)

SELECT COUNTRY, AVG(PER_CAPITA_PROD) 
AS AVG_PROD_PER_CAPITA FROM PER_CAPITA
GROUP BY COUNTRY
ORDER BY AVG_PROD_PER_CAPITA DESC LIMIT 10;

-- SELECT P.COUNTRY, SUM(P.PRODUCTION) AS TOTAL_PRODUCTION, SUM(PO.VALUE) AS TOTAL_POPULATION,
-- SUM(P.PRODUCTION)/SUM(PO.VALUE) AS PRODUCTION_PER_CAPITA
-- FROM PRODUCTION P 
-- JOIN POPULATION PO
-- ON P.COUNTRY = PO.COUNTRIES 
-- AND P.YEAR = PO.YEAR
-- GROUP BY P.COUNTRY
-- ORDER BY PRODUCTION_PER_CAPITA DESC; 
select * from population;


-- 16) Which countries have improved (reduced) their per capita emissions the most over the last decade?
WITH PER_CAP AS (
    SELECT 
        E.COUNTRY,
        E.YEAR,
        E.EMISSION / P.VALUE AS PER_CAPITA_EMISSION,
        FIRST_VALUE(E.EMISSION / P.VALUE) 
            OVER (PARTITION BY E.COUNTRY ORDER BY E.YEAR) AS FIRST_YEAR_PCE,
        LAST_VALUE(E.EMISSION / P.VALUE) 
            OVER (PARTITION BY E.COUNTRY ORDER BY E.YEAR 
                  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_YEAR_PCE
    FROM EMISSION_TOTAL E JOIN POPULATION P	ON E.COUNTRY = P.COUNTRIES
	AND E.YEAR = P.YEAR
)
SELECT 
    COUNTRY, 
    FIRST_YEAR_PCE AS START_PCE,
    LAST_YEAR_PCE AS END_PCE,
    (FIRST_YEAR_PCE - LAST_YEAR_PCE) AS IMPROVED_BY
FROM PER_CAP
GROUP BY COUNTRY, FIRST_YEAR_PCE, LAST_YEAR_PCE
ORDER BY IMPROVED_BY DESC LIMIT 10;


-- 17) What is the global share (%) of emissions by country?
WITH COUNTRY_EMISSION AS (
SELECT COUNTRY, SUM(EMISSION) AS TOTAL_EMISSION FROM EMISSION_TOTAL GROUP BY COUNTRY
)
SELECT C.COUNTRY, C.TOTAL_EMISSION, (C.TOTAL_EMISSION * 100.0 / SUM(TOTAL_EMISSION) OVER ()) AS GLOBAL_SHARE
FROM COUNTRY_EMISSION C ORDER BY GLOBAL_SHARE DESC;


WITH COUNTRY_EMISSION AS (
SELECT COUNTRY, SUM(EMISSION) AS TOTAL_EMISSION 
FROM EMISSION_3 GROUP BY COUNTRY
),
GLOBAL_EMISSION AS(
SELECT SUM(TOTAL_EMISSION) AS GLOBAL_EMIS FROM COUNTRY_EMISSION)
SELECT C.COUNTRY, C.TOTAL_EMISSION, 
(C.TOTAL_EMISSION * 100.0 / G.GLOBAL_EMIS) AS GLOBAL_SHARE
FROM COUNTRY_EMISSION C, GLOBAL_EMISSION G 
ORDER BY GLOBAL_SHARE DESC;






-- 18) What is the global average GDP, emission, and population by year?
select distinct year from GDP_3;
select distinct year from emission_3;
select distinct year from population;

WITH GDP_YEAR AS(
SELECT YEAR, AVG(VALUE) AS AVG_GDP FROM GDP_3 GROUP BY YEAR
),
POP_YEAR AS(
SELECT YEAR, AVG(VALUE) AS AVG_POP FROM POPULATION GROUP BY year
),
EMI_YEAR AS(
SELECT YEAR, AVG(EMISSION) AS AVG_EMI FROM EMISSION_TOTAL GROUP BY YEAR
),
GDP_POP AS(
SELECT G.YEAR, G.AVG_GDP, P.AVG_POP FROM GDP_YEAR G
LEFT JOIN POP_YEAR P
ON G.YEAR = P.YEAR
),
FINAL AS(
SELECT GP.YEAR,GP.AVG_GDP,GP.AVG_POP, E.AVG_EMI FROM GDP_POP GP
LEFT JOIN EMI_YEAR E ON GP.YEAR = E.YEAR
)
SELECT * FROM FINAL ORDER BY YEAR;

-- CHANGE 
 
WITH GDP_YEAR AS(
SELECT YEAR, AVG(VALUE) AS AVG_GDP FROM GDP_3 GROUP BY YEAR
),
POP_YEAR AS(
SELECT YEAR, AVG(VALUE) AS AVG_POP FROM POPULATION GROUP BY year
),
EMI_YEAR AS(
SELECT YEAR, AVG(EMISSION) AS AVG_EMI FROM EMISSION_TOTAL GROUP BY YEAR
)
SELECT E.YEAR,G.AVG_GDP,P.AVG_POP, E.AVG_EMI FROM EMI_YEAR E 
JOIN POP_YEAR P ON  E.YEAR = P.YEAR 
JOIN GDP_YEAR G ON  P.YEAR = G.YEAR
ORDER BY E.YEAR;















-- Without CTE
SELECT G.YEAR, G.AVG_GDP, P.AVG_POP, E.AVG_EMI FROM
(SELECT YEAR, AVG(VALUE) AS AVG_GDP FROM GDP_3 GROUP BY YEAR) G
LEFT JOIN 
(SELECT YEAR, AVG(VALUE) AS AVG_POP FROM POPULATION GROUP BY YEAR) P
ON G.YEAR = P.YEAR
LEFT JOIN
(SELECT YEAR, AVG(EMISSION) AS AVG_EMI FROM EMISSION_3 GROUP BY YEAR) E
ON G.YEAR = E.YEAR
ORDER BY YEAR;

select * from emission_3;
